POST http://localhost:9888/save
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="par.jpg"
Content-Type: text/plain

dfdfdfdf
--WebAppBoundary--

###

GET http://localhost:9888/media/b8436435-9388-4c73-b1d0-c1fcfe951104

###
POST https://auth-servisss.herokuapp.com/api/tokens
Content-Type: application/json

{
  "username": "RendL",
  "password": "pass"
}

> {% client.global.set("auth_token", response.body.token); %}

###